# Generated by Django 5.2.1 on 2025-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
