# Generated by Django 5.2.1 on 2025-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detectionhistory_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
