# Generated by Django 5.2.1 on 2025-06-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_detectionhistory_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
