# Generated by Django 5.2.1 on 2025-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_detectionhistory_city_detectionhistory_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionhistory',
            name='filepath',
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
