# Generated by Django 5.2.1 on 2025-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_remove_detectionhistory_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionhistory',
            name='file',
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='filepath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
